@extends('layouts.admin')
@section('title', 'Laporan Kas & Bank')
@section('breadcrumb')<nav class="page-breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="#">Report</a></li><li class="breadcrumb-item active">Kas &amp; Bank</li></ol></nav>@endsection
@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="page-title mb-1">Laporan Kas &amp; Bank</h4><span class="text-muted">Saldo dan mutasi per rekening untuk periode yang dipilih.</span></div></div>
    <form method="GET" class="card mb-3"><div class="card-body py-3"><div class="row align-items-end g-2"><div class="col-sm-5 col-md-3"><label for="from_date" class="form-label mb-1">Dari Tanggal</label><input id="from_date" name="from_date" type="date" class="form-control form-control-sm" value="{{ $fromDate }}" required></div><div class="col-sm-5 col-md-3"><label for="to_date" class="form-label mb-1">Sampai Tanggal</label><input id="to_date" name="to_date" type="date" class="form-control form-control-sm" value="{{ $toDate }}" required></div><div class="col-sm-2 col-md-auto"><button class="btn btn-sm btn-primary" type="submit"><i data-feather="filter" class="icon-sm me-1"></i>Tampilkan</button> <button class="btn btn-sm btn-outline-success" type="submit" formaction="{{ route('super.reports.cash-bank.export') }}"><i data-feather="download" class="icon-sm me-1"></i>Export Excel</button></div></div></div></form>
    <div class="row g-3 mb-3"><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Rekening</div><div class="fs-5 fw-semibold">{{ number_format($summary['accounts']) }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Saldo Awal Periode</div><div class="fs-5 fw-semibold">Rp {{ number_format($summary['opening'], 2, ',', '.') }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Kas Masuk</div><div class="fs-5 fw-semibold text-success">Rp {{ number_format($summary['incoming'], 2, ',', '.') }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Kas Keluar</div><div class="fs-5 fw-semibold text-danger">Rp {{ number_format($summary['outgoing'], 2, ',', '.') }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Saldo Akhir Periode</div><div class="fs-5 fw-semibold">Rp {{ number_format($summary['closing'], 2, ',', '.') }}</div></div></div></div></div>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Rekening</th><th>Jenis</th><th class="text-end">Saldo Awal</th><th class="text-end">Masuk</th><th class="text-end">Keluar</th><th class="text-end">Saldo Akhir</th><th>Status</th></tr></thead><tbody>
        @forelse($accounts as $account)
            <tr><td>{{ $account->code }}</td><td>{{ $account->name }}@if($account->type === 'bank' && $account->bank_name)<div class="small text-muted">{{ $account->bank_name }} · {{ $account->account_number ?: 'Nomor rekening belum diisi' }}</div>@endif</td><td>{{ $account->type === 'cash' ? 'Kas' : 'Bank' }}</td><td class="text-end">Rp {{ number_format($account->report_opening, 2, ',', '.') }}</td><td class="text-end text-success">Rp {{ number_format($account->report_incoming, 2, ',', '.') }}</td><td class="text-end text-danger">Rp {{ number_format($account->report_outgoing, 2, ',', '.') }}</td><td class="text-end fw-semibold">Rp {{ number_format($account->report_closing, 2, ',', '.') }}</td><td><span class="badge {{ $account->is_active ? 'bg-success' : 'bg-secondary' }}">{{ $account->is_active ? 'Aktif' : 'Nonaktif' }}</span></td></tr>
        @empty
            <tr><td colspan="8" class="text-center text-muted py-4">Belum ada rekening kas/bank untuk perusahaan ini.</td></tr>
        @endforelse
        </tbody></table></div></div></div>
@endsection
