@extends('layouts.admin')
@section('title', 'Laporan Inventory')
@section('breadcrumb')<nav class="page-breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="#">Report</a></li><li class="breadcrumb-item active">Inventory</li></ol></nav>@endsection
@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="page-title mb-1">Laporan Inventory</h4><span class="text-muted">Ringkasan pergerakan kuantitas barang berdasarkan Stock Card.</span></div></div>
    <form method="GET" class="card mb-3"><div class="card-body py-3"><div class="row align-items-end g-2"><div class="col-sm-5 col-md-3"><label for="from_date" class="form-label mb-1">Dari Tanggal</label><input id="from_date" name="from_date" type="date" class="form-control form-control-sm" value="{{ $fromDate }}" required></div><div class="col-sm-5 col-md-3"><label for="to_date" class="form-label mb-1">Sampai Tanggal</label><input id="to_date" name="to_date" type="date" class="form-control form-control-sm" value="{{ $toDate }}" required></div><div class="col-sm-2 col-md-auto"><button class="btn btn-sm btn-primary" type="submit"><i data-feather="filter" class="icon-sm me-1"></i>Tampilkan</button> <button class="btn btn-sm btn-outline-success" type="submit" formaction="{{ route('super.reports.inventory.export') }}"><i data-feather="download" class="icon-sm me-1"></i>Export Excel</button></div></div></div></form>
    <div class="row g-3 mb-3"><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Barang Dilacak</div><div class="fs-5 fw-semibold">{{ number_format($summary['products']) }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Barang dengan Mutasi</div><div class="fs-5 fw-semibold">{{ number_format($summary['moved_products']) }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Stok Aman</div><div class="fs-5 fw-semibold text-success">{{ number_format($summary['safe_stock']) }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Stok Rendah</div><div class="fs-5 fw-semibold text-warning">{{ number_format($summary['low_stock']) }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Stok Habis</div><div class="fs-5 fw-semibold text-danger">{{ number_format($summary['out_of_stock']) }}</div></div></div></div></div>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Barang</th><th>Kategori</th><th>Satuan</th><th class="text-end">Saldo Awal</th><th class="text-end">Masuk</th><th class="text-end">Keluar</th><th class="text-end">Saldo Akhir</th><th>Status</th></tr></thead><tbody>
        @forelse($products as $product)
            <tr><td><a href="{{ route('super.stock-card.index', ['product_id' => $product->id]) }}">{{ $product->code }}</a></td><td>{{ $product->name }}</td><td>{{ $product->category?->name ?? '—' }}</td><td>{{ $product->unit?->symbol ?: $product->unit?->name ?: '—' }}</td><td class="text-end">{{ number_format($product->report_opening, 4, ',', '.') }}</td><td class="text-end">{{ number_format($product->report_incoming, 4, ',', '.') }}</td><td class="text-end">{{ number_format($product->report_outgoing, 4, ',', '.') }}</td><td class="text-end fw-semibold">{{ number_format($product->report_closing, 4, ',', '.') }}</td><td><span class="badge {{ $product->report_status === 'Aman' ? 'bg-success' : ($product->report_status === 'Habis' ? 'bg-danger' : 'bg-warning text-dark') }}">{{ $product->report_status }}</span></td></tr>
        @empty
            <tr><td colspan="9" class="text-center text-muted py-4">Belum ada barang yang melacak stok.</td></tr>
        @endforelse
        </tbody></table></div></div></div>
@endsection
