@extends('layouts.admin')
@section('title', 'Laporan Penjualan')
@section('breadcrumb')<nav class="page-breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="#">Report</a></li><li class="breadcrumb-item active">Penjualan</li></ol></nav>@endsection
@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="page-title mb-1">Laporan Penjualan</h4><span class="text-muted">Invoice yang sudah diterbitkan beserta pembayaran dan sisa piutangnya.</span></div></div>
    <form method="GET" class="card mb-3"><div class="card-body py-3"><div class="row align-items-end g-2"><div class="col-sm-5 col-md-3"><label for="from_date" class="form-label mb-1">Dari Tanggal</label><input id="from_date" name="from_date" type="date" class="form-control form-control-sm" value="{{ $fromDate }}" required></div><div class="col-sm-5 col-md-3"><label for="to_date" class="form-label mb-1">Sampai Tanggal</label><input id="to_date" name="to_date" type="date" class="form-control form-control-sm" value="{{ $toDate }}" required></div><div class="col-sm-2 col-md-auto"><button class="btn btn-sm btn-primary" type="submit"><i data-feather="filter" class="icon-sm me-1"></i>Tampilkan</button> <button class="btn btn-sm btn-outline-success" type="submit" formaction="{{ route('super.reports.sales.export') }}"><i data-feather="download" class="icon-sm me-1"></i>Export Excel</button></div></div></div></form>
    <div class="row g-3 mb-3"><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Penjualan</div><div class="fs-5 fw-semibold">Rp {{ number_format($summary['total'], 2, ',', '.') }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Pajak</div><div class="fs-5 fw-semibold">Rp {{ number_format($summary['tax'], 2, ',', '.') }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Dibayar</div><div class="fs-5 fw-semibold text-success">Rp {{ number_format($summary['paid'], 2, ',', '.') }}</div></div></div></div><div class="col-md"><div class="card h-100"><div class="card-body"><div class="text-muted small">Sisa Piutang</div><div class="fs-5 fw-semibold text-warning">Rp {{ number_format($summary['outstanding'], 2, ',', '.') }}</div></div></div></div></div>
    <div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-bordered table-hover align-middle mb-0"><thead><tr><th>Nomor Invoice</th><th>Tanggal</th><th>Customer</th><th class="text-end">Subtotal</th><th class="text-end">Pajak</th><th class="text-end">Total</th><th class="text-end">Dibayar</th><th class="text-end">Sisa</th></tr></thead><tbody>
        @forelse($invoices as $invoice)
            @php($paid = (float) $invoice->paid_total)
            <tr><td>{{ $invoice->number }}</td><td>{{ $invoice->invoice_date?->format('d/m/Y') }}</td><td>{{ $invoice->customer?->name ?? 'Customer dihapus' }}</td><td class="text-end">Rp {{ number_format($invoice->subtotal, 2, ',', '.') }}</td><td class="text-end">Rp {{ number_format($invoice->tax_amount, 2, ',', '.') }}</td><td class="text-end">Rp {{ number_format($invoice->total_amount, 2, ',', '.') }}</td><td class="text-end">Rp {{ number_format($paid, 2, ',', '.') }}</td><td class="text-end">Rp {{ number_format(max(0, (float) $invoice->total_amount - $paid), 2, ',', '.') }}</td></tr>
        @empty
            <tr><td colspan="8" class="text-center text-muted py-4">Belum ada Sales Invoice diterbitkan pada periode ini.</td></tr>
        @endforelse
        </tbody></table></div></div></div>
@endsection
