<!doctype html>
<html lang="id"><head><meta charset="utf-8"><title>{{ $invoice->number }}</title><style>
    @page{margin:32px 36px}body{font-family:DejaVu Sans,sans-serif;color:#202938;font-size:11px}h1{font-size:20px;margin:0 0 4px}.muted{color:#667085}
    .company-header{width:100%;border-bottom:1px solid #cfd5df;padding-bottom:10px;margin-bottom:16px}.company-logo-cell{width:90px;vertical-align:middle}.company-logo-cell img{max-width:76px;max-height:62px}.company-info{vertical-align:middle;line-height:1.5}.company-name{font-size:16px;font-weight:bold;color:#263b5e;margin-bottom:2px}.company-contact{color:#475467}
    .header{border-bottom:2px solid #263b5e;padding-bottom:14px;margin-bottom:18px}.number{font-size:13px;font-weight:bold;color:#263b5e}table.meta{width:100%;margin-bottom:18px}.meta td{padding:4px 8px 4px 0;vertical-align:top}.meta .label{width:120px;color:#667085}
    table.items{border-collapse:collapse;width:100%}.items th,.items td{border:1px solid #cfd5df;padding:6px 5px}.items th{background:#f1f4f8;text-align:left}.right{text-align:right}.center{text-align:center}.total{font-weight:bold;background:#f1f4f8}
    .note{border:1px solid #cfd5df;padding:8px;white-space:pre-line}.signatures{width:100%;margin-top:38px}.signatures td{width:50%;text-align:center;padding:8px 18px}.sign-line{border-bottom:1px solid #475467;height:48px;margin-bottom:6px}.footer{margin-top:20px;border-top:1px solid #d0d5dd;padding-top:7px;font-size:9px;color:#667085}
    </style></head><body>
    @include('super.documents.partials.company-pdf-header', ['company' => $company, 'companyLogoDataUri' => $companyLogoDataUri])
    <div class="header"><h1>Sales Invoice</h1><div class="muted">Tagihan penjualan atas barang yang telah dikirim</div><div class="number">{{ $invoice->number }}</div></div>
    <table class="meta"><tr><td class="label">Customer</td><td>{{ $invoice->customer?->name ?? 'Customer dihapus' }}</td><td class="label">Tanggal Invoice</td><td>{{ $invoice->invoice_date?->format('d/m/Y') }}</td></tr>
        <tr><td class="label">Alamat</td><td>{{ $invoice->customer?->address ?: '—' }}{{ $invoice->customer?->city ? ', '.$invoice->customer->city : '' }}</td><td class="label">Jatuh Tempo</td><td>{{ $invoice->due_date?->format('d/m/Y') ?? '—' }}</td></tr>
        <tr><td class="label">Kontak</td><td>{{ $invoice->customer?->phone ?: '—' }} · {{ $invoice->customer?->email ?: '—' }}</td><td class="label">Delivery / SO</td><td>{{ $invoice->delivery?->number ?? '—' }} / {{ $invoice->salesOrder?->number ?? '—' }}</td></tr>
        <tr><td class="label">Status</td><td>{{ $invoice->status === 'issued' ? 'Diterbitkan' : 'Draft' }}</td><td class="label">Diterbitkan</td><td>{{ $invoice->issued_at?->format('d/m/Y H:i') ?? 'Belum diterbitkan' }}</td></tr></table>
    <table class="items"><thead><tr><th class="center" style="width:28px">No</th><th>Barang</th><th class="right" style="width:58px">Jumlah</th><th class="right" style="width:80px">Harga</th><th class="right" style="width:70px">Diskon</th><th class="right" style="width:50px">Pajak</th><th class="right" style="width:90px">Total</th></tr></thead><tbody>
        @forelse($invoice->items as $item)<tr><td class="center">{{ $loop->iteration }}</td><td>{{ $item->product?->code ?? '—' }}<br>{{ $item->product?->name ?? 'Barang dihapus' }}</td><td class="right">{{ number_format((float)$item->quantity,4,',','.') }} {{ $item->product?->unit?->symbol ?: $item->product?->unit?->name }}</td><td class="right">Rp {{ number_format((float)$item->unit_price,2,',','.') }}</td><td class="right">Rp {{ number_format((float)$item->discount_amount,2,',','.') }}</td><td class="right">{{ number_format((float)$item->tax_rate,2,',','.') }}%</td><td class="right">Rp {{ number_format((float)$item->line_total,2,',','.') }}</td></tr>
        @empty<tr><td colspan="7" class="center">Tidak ada barang.</td></tr>@endforelse
        <tr><th colspan="6" class="right">Subtotal</th><td class="right">Rp {{ number_format((float)$invoice->subtotal,2,',','.') }}</td></tr><tr><th colspan="6" class="right">Total Pajak</th><td class="right">Rp {{ number_format((float)$invoice->tax_amount,2,',','.') }}</td></tr><tr class="total"><th colspan="6" class="right">Total Tagihan</th><td class="right">Rp {{ number_format((float)$invoice->total_amount,2,',','.') }}</td></tr>
    </tbody></table>
    @if($invoice->notes)<p><strong>Catatan / Syarat Pembayaran:</strong></p><div class="note">{{ $invoice->notes }}</div>@endif
    <table class="signatures"><tr><td>Customer<div class="sign-line"></div>{{ $invoice->customer?->name ?? '—' }}</td><td>{{ $company?->name ?: 'Perusahaan' }}<div class="sign-line"></div>{{ $invoice->issuer?->name ?? $invoice->creator?->name ?? '—' }}</td></tr></table>
    <div class="footer">Sales Invoice {{ $invoice->number }} · Dicetak {{ now()->format('d/m/Y H:i') }}.</div>
</body></html>
